const IPC_SELECTOR = 'IPC_SELECTOR'
const IPC_REFRESH_TICKETS = 'IPC_REFRESH_TICKETS'
const IPC_REFRESH_PRS = 'IPC_REFRESH_PRS'
const IPC_REFRESH_GIT = 'IPC_REFRESH_GIT'
const IPC_CHECKOUT_LOCAL_BRANCH = 'IPC_CHECKOUT_LOCAL_BRANCH'
const IPC_CREATE_BRANCH = 'IPC_CREATE_BRANCH'
const IPC_REBASE_BRANCH = 'IPC_REBASE_BRANCH'
const IPC_DELETE_BRANCH = 'IPC_DELETE_BRANCH'
const IPC_PUSH_BRANCH = 'IPC_PUSH_BRANCH'
const IPC_CANCEL_SELECT = 'IPC_CANCEL_SELECT'
const IPC_HIDE_SELECT = 'IPC_HIDE_SELECT'
const IPC_REPO_SELECT = 'IPC_REPO_SELECT'

export {
  IPC_SELECTOR,
  IPC_REFRESH_TICKETS,
  IPC_REFRESH_PRS,
  IPC_REFRESH_GIT,
  IPC_CHECKOUT_LOCAL_BRANCH,
  IPC_CREATE_BRANCH,
  IPC_REBASE_BRANCH,
  IPC_DELETE_BRANCH,
  IPC_PUSH_BRANCH,
  IPC_CANCEL_SELECT,
  IPC_REPO_SELECT,
  IPC_HIDE_SELECT,
}
